### ISSUE TITLE
Register Button Does not Work

### ISSUE THREAD

**Issue by marielaskey** [lk00044/MLJFurnitureStore#36]
![image](https://github.com/lk00044/MLJFurnitureStore/assets/42015438/debd690a-b51c-4090-ab47-7db55989dc35)

**Comment by lk00044** [comment]
I tried it and it worked.

**Comment by marielaskey** [comment]
From Yang's feedback: the program reported "failed to register customer", it's unclear why (image 2)

**Comment by lk00044** [comment]
should be fixed
