### ISSUE TITLE
Forms: Login/Logout

### ISSUE THREAD

**Issue by lk00044** [lk00044/MLJFurnitureStore#4]

**Comment by lk00044** [comment]
log in and log out (Currently, you may store the password as plain text in the DB. However, in future iterations, I expect to see you s**tore hashed passwords** in the DB. Just keep it in mind)
**Display the name and username of the user who is logged in on all the views**

**Comment by lk00044** [comment]
Create the controller and DAL methods as needed.

**Comment by lk00044** [comment]
Read for review

**Comment by marielaskey** [comment]
> log in and log out (Currently, you may store the password as plain text in the DB. However, in future iterations, I expect to see you s**tore hashed passwords** in the DB. Just keep it in mind) **Display the name and username of the user who is logged in on all the views**

There is an encryption helper now. That should probably also be reviewed/tested.

**Comment by marielaskey** [comment]
Complete and merged to master
