### ISSUE TITLE
Update Member-  Zip/Phone Validation 

### ISSUE THREAD

**Issue by marielaskey** [lk00044/MLJFurnitureStore#52]
-no field validation on zip, phone number

**Comment by lk00044** [comment]
done

**Comment by lk00044** [comment]
but test it please.

**Comment by marielaskey** [comment]
@lk00044 is there a PR for this?

**Comment by lk00044** [comment]
It’s part of the update members that I’m doing. No PR yet. I am adding the
“enhancement” as well. Almost done though. You can see it in my
updatemember branch if you want to pull it to an empty project.

Also not merging until the ok from Jonathan as he is doing something that
might break. Not sure what. He just ask us not to merge.

I should have all feedback addressed tomorrow. I’ll start view then.

Leslie
