### ISSUE TITLE
Iteration 1 Feedback - Update member

### ISSUE THREAD

**Issue by lk00044** [lk00044/MLJFurnitureStore#64]
update member:-11
-1, dob should not contain time
-1, state and gender comboboxes should not be editable
-4, no field validation on zip, phone number
-1, need to be able to reset the fields
-2, what if there are multiple matches? only one will be loaded for update (it would be nice if after a search is done, the user can click on a row  in a datagriview to select the member and then the member information is loaded automatically in a  edit member dialog box). What you have is ok. This is just a suggestion from the perspective of user-friendliness and ease of use. 
 
-1,  need to show memberID after a member is loaded --how can one perform member id search if one cannot see it anywhere?
-1, incorrect tab orders for some fields

**Comment by marielaskey** [comment]
Ticket 54, 55, 52, and 46 cover this feedback.
